input {
  tcp {
    port => 5000
    codec => json_lines # one JSON object per line
  }
}

filter {
  if ![@timestamp] {
    mutate { add_field => { "@timestamp" => "%{+ISO8601}" } }
  }

  mutate {
    add_field => { "service" => "node-app" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "node-logs-%{+YYYY.MM.dd}" # node-logs-2026.03.03 store logs into daily index
  }

 # prints every processed event into logstash container
  stdout { codec => rubydebug }
}